--hemograma
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Hemáceas','HEM', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Hemoglobina','HB', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Hematócrito','HCT', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Hemoglobina Corpuscular Média','HCM', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Volume Corpuscular Médio','VCM', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Concentração de Hemoglobina Corpuscular Média','CHCM', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Leucócitos','LEUC', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Segmentados','SEG', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('EOS','EOS', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('BAS','BAS', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('LINF','LINF', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('LINFATÍPC','LINFATÍPC', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('MONO','MONO', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('HEMTSC','HEMTSC', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('VHS1ª','VHS1ª', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('VHS2ª','VHS2ª', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('PQT','PQT', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('PQTÓCT','PQTÓCT', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('T. COAG.','T. COAG.', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('T. SANG.','T. SANG.', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('TAP','TAP', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('TAP %','TAP %', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('TTP','TTP', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('RETIC ABS','TTP', 1);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('RETIC %','TTP', 1);
--eas

insert into public.exame(nome, sigla, id_tipoexame)VALUES ('DENS','DENS', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('Ph','Ph', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('ALB','ALB', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('GLIC','GLIC', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('C.CETON','C.CETON', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('UROBIL','UROBIL', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('NITRITO','NITRITO', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('BILIRR','BILIRR', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('CEL.EPT','CEL.EPT', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('LEUC','LEUC', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('HEM','HEM', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('CILIND','CILIND', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('BACT','BACT', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('CRISTAIS','CRISTAIS', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('FIL.MUCO','FIL.MUCO', 2);
insert into public.exame(nome, sigla, id_tipoexame)VALUES ('OBS','OBS', 2);
