INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (1,'Hemograma');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (2,'EAS');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (3,'Dosagens Hormonais');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (4,'Lipidogramas');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (5,'Parametros de Acompanhamento do HIV');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (6,'Parasitológico');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (7,'Bioquímica');
INSERT INTO public.tipoexame(id_tipoexame, nome) VALUES (8,'Provas de Função Hepática');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (9,'Exames Diretos e Culturas');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (10,'Especialidades');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (11,'Raio X');
INSERT INTO public.tipoexame(id_tipoexame, nome)VALUES (12,'Eletrocardiogramas');