insert into public.tipoexame(nome)VALUES ('Hemograma');
insert into public.tipoexame(nome)VALUES ('EAS');
insert into public.tipoexame(nome)VALUES ('Dosagens Hormonais');
insert into public.tipoexame(nome)VALUES ('Lipidogramas');
insert into public.tipoexame(nome)VALUES ('Parametros de Acompanhamento do HIV');
insert into public.tipoexame(nome)VALUES ('Parasitológico');
insert into public.tipoexame(nome)VALUES ('Parasitológico');
insert into public.tipoexame(nome)VALUES ('Bioquímica');
insert into public.tipoexame(nome)VALUES ('Provas de Função Hepática');
insert into public.tipoexame(nome)VALUES ('Exames Diretos e Culturas');
insert into public.tipoexame(nome)VALUES ('Especialidades');
insert into public.tipoexame(nome)VALUES ('Raio X');
insert into public.tipoexame(nome)VALUES ('Eletrocardiogramas');
insert into public.tipoexame(nome)VALUES ('Laudo - Raio X');
insert into public.tipoexame(nome)VALUES ('Laudo - Eletrocardiograma');
insert into public.tipoexame(nome)VALUES ('Laudo - Especialidades');
insert into public.tipoexame(nome)VALUES ('Exames Diretos e Culturas');
insert into public.tipoexame(nome)VALUES ('Eletroneuromiografia');
insert into public.tipoexame(nome)VALUES ('Tomografia');
insert into public.tipoexame(nome)VALUES ('Outros Diagnósticos por Imagem');
insert into public.tipoexame(nome)VALUES ('Avaliação Tisiológica');
insert into public.tipoexame(nome)VALUES ('Endoscopias');
insert into public.tipoexame(nome)VALUES ('Ecografias');
